version: '3.9'

services:
  app:
    build: .
    container_name: safebot_app
    command: 'python /app/safebot/run.py'
    volumes:
      # If you want to prevent accidental file substitution, comment this out
      - ./safebot:/app/safebot
      # Store pyrogram sessions in a separate directory
      - ./session:/app/session
      # Mount, as all migrations are executed inside docker
      - ./migrations:/app/migrations
      # Locales that application will be used when sending messages
      - ./locales:/app/locales
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: safebot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env

volumes:
  pgdata: null