version: '3.9'

services:
  app:
    build: .
    container_name: safebot_app
    command: 'python /app/safebot/run.py'
    volumes:
      # Store pyrogram sessions in a separate directory
      - ./session:/app/session
      # Locales that application will be used when sending messages
      - ./locales:/app/locales
    env_file: .env
    depends_on:
      - db
    networks:
      - safebot-net

  db:
    image: postgres:16
    container_name: safebot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    networks:
      - safebot-net

volumes:
  pgdata: null

networks:
  safebot-net:
    external:
      name: 'safebot_network'